##
# Operational services to run the application in your local environment.
##
version: '3.1'

services:
  # Container to run Apache/PHP
  www:
    env_file:
      - .env
    build: env/dev/php
    hostname: "${PROJECT_NAME}"
    network_mode: "bridge"
    domainname: "${PROJECT_NAME}.vm"
    container_name: "${PROJECT_NAME}_www"
    environment:
      DNSDOCK_NAME: www
      DNSDOCK_IMAGE: ${PROJECT_NAME}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      VIRTUAL_HOST: "www.${PROJECT_NAME}.vm"
    links:
      - db
    volumes:
      - .:/var/www/html/

  # Container to run our database
  db:
    env_file:
      - .env
    image: mariadb:$MARIADB_TAG
    restart: always
    network_mode: "bridge"
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      DNSDOCK_NAME: db
      DNSDOCK_IMAGE: ${PROJECT_NAME}
    volumes:
      - ./database:/var/lib/mysql
